version: 2.1

jobs:
  lint-app:
    docker:
      - image: cimg/node:14.15.4
        
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container 
          command: |
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed:v3b ./udagram-api-feed:v3b
            docker tag udagram-api-feed:v3b beakalyk/udagram-api-feed:v3b
            docker build -t udagram-api-user:v3b ./udagram-api-user:v3b
            docker tag udagram-api-user:v3b beakalyk/udagram-api-user:v3b
            docker build -t udagram-frontend:v3b ./udagram-frontend:v3b
            docker tag udagram-frontend:v3b beakalyk/udagram-frontend:v3b
            docker build -t reverseproxy:v3b ./udagram-reverseproxy:v3b
            docker tag reverseproxy:v3b beakalyk/reverseproxy:v3b
            echo "-------- All images succesfully built----------"
            docker login -u beakalyk -p $DOCKER_PASSWORD
            echo " ------- login in to hub--------"
            echo "-------------- Pushing images to dockerhub-------"
            docker push beakalyk/udagram-api-feed:v3b
            docker push beakalyk/udagram-api-user:v3b
            docker push beakalyk/udagram-frontend:v3b
            docker push beakalyk/reverseproxy:v3b
            
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]